apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

resources:
  - dbclaim-pvc.yaml
nameprefix: prod-
images:
  - name: mysql
    newName: registry.redhat.io/rhel8/mysql-80
    newTag: 1-156
